name = "ElectricityEmissions"
uuid = "071d0d29-39bd-4f04-b4db-7866826f86bf"
authors = ["Joe Gorka <jgorka@wisc.edu>, Noah Rhodes <nrhodes@lanl.gov>, Line Roald <roald@wisc.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
